# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.2.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: true
odoo_version: 14.0
rebel_module_groups: []
repo_description: AldaHotels custom modules
repo_name: Aldahotels Custom modules
repo_slug: aldahotels
travis_apt_packages: []
travis_apt_sources: []
